spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: master
        git:
          uri: https://github.com/omerosmann/Config-Server-E-commerce
server:
  port: 8888